version: '2'
services:
  wp_db:
    image: mysql:5.7
    container_name: ${NOME_SITE}_db
    volumes:
      - ${NOME_SITE}_db:/var/lib/mysql
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASS}
    network_mode: bridge

  wp_html:
    container_name: ${NOME_SITE}_html
    image: wordpress:latest
    working_dir: /var/www/html
    volumes:
      - ${NOME_SITE}_html:/var/www/html
      - ${NOME_SITE}_conf.d:/usr/local/etc/php/conf.d
    ports:
      - 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_DB_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_DB_PASS}
      WORDPRESS_DB_NAME: ${NOME_SITE}
      VIRTUAL_HOST: ${URL_SITE}
      LETSENCRYPT_HOST: ${URL_SITE}
      LETSENCRYPT_EMAIL: suporte@agenciamobidick.com.br
    network_mode: bridge
